Parameters: 
    EnvType:
        Description: "Environment type."
        Default: test
        Type: String
        AllowedValues:
            - test
            - prod
        ConstraintDescription: "must specify test or prod."
    ConfigStackName:
        Description: "Name of config stack."
        Default: scd-config
        Type: String
Resources:
    StellarApi:
        Type: "AWS::CloudFormation::Stack"
        Properties:
            TemplateURL:
                Fn::ImportValue: !Sub "${ConfigStackName}-StellarTemplateURL"
            Parameters:
                CodeS3BucketName:
                    Fn::ImportValue: !Sub "${ConfigStackName}-S3BucketName"
    UsersAndRoles:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: StellarApi
        Properties:
            TemplateURL:
                Fn::ImportValue: !Sub "${ConfigStackName}-IAMTemplateURL"
            Parameters:
                EnvType: !Ref EnvType
                StellarLambdaApiArn: !GetAtt StellarApi.Outputs.StellarLambdaApiArn
                StellarHttpApiArn: !GetAtt StellarApi.Outputs.StellarHttpApiArn
                ConfigS3BucketArn:
                    Fn::ImportValue: !Sub "${ConfigStackName}-S3BucketArn" 
