AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
    ScdCodeBucketName:
        Type: String
        Description: Name of S3 bucket to store code.
    PythonLambdaPackage:
        Type: String
        Default: stellar_api.zip
        Description: Name of python lambda code package.
Resources:
    CodeS3Bucket:
        Type: "AWS::S3::Bucket"
        DeletionPolicy: Retain
        Properties:
            BucketName: !Ref ScdCodeBucketName
            VersioningConfiguration:
                Status: Enabled
    StellarSectorsTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions:
                -
                  AttributeName: sector_group
                  AttributeType: S
                -
                  AttributeName: sector_id
                  AttributeType: S
            KeySchema:
                -
                  AttributeName: sector_group
                  KeyType: HASH
                -
                  AttributeName: sector_id
                  KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
            TableName: stellar_sectors
    StellarSystemsTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions:
                -
                  AttributeName: sector_id
                  AttributeType: S
                -
                  AttributeName: system_name
                  AttributeType: S
            KeySchema:
                -
                  AttributeName: sector_id
                  KeyType: HASH
                -
                  AttributeName: system_name
                  KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
            TableName: stellar_systems
    SystemSearchesTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions:
                -
                  AttributeName: system_prefix
                  AttributeType: S
                -
                  AttributeName: system_name
                  AttributeType: S
            KeySchema:
                -
                  AttributeName: system_prefix
                  KeyType: HASH
                -
                  AttributeName: system_name
                  KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
            TableName: system_searches

    StellarAPILambda:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri:
                Bucket: !Ref ScdCodeBucketName
                Key: !Ref PythonLambdaPackage
            Handler: stellar_code_function.handler
            Runtime: python3.6
            Policies: AmazonDynamoDBFullAccess
            Events:
                HttpPost:
                    Type: Api
                    Properties:
                        Path: '/stellar/code'
                        Method: post
                        RestApiId: !Ref StellarHttpApi
    StellarHttpApi:
        Type: 'AWS::Serverless::Api'
        Properties:
            StageName: Prod
            DefinitionBody:
                swagger: '2.0'
                info:
                    title: scd
                paths:
                    '/stellar/code':
                        post:
                            responses:
                                '200':
                                    description: OK
                                    content:
                                        'application/json':
                                            schema: Empty
                            consumes:
                            - 'application/json'
                            produces:
                            - 'application/json'
                            x-amazon-apigateway-request-validator: basic
                            x-amazon-apigateway-integration:
                                httpMethod: POST
                                type: AWS_PROXY
                                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StellarAPILambda.Arn}/invocations'
                                passThroughBehavior: when_no_match
                                responses:
                                    default:
                                        statusCode: '200'
                                        responseTemplates:
                                            'application/json': ''
Outputs:
    CodeS3BucketArn:
        Value: !Ref CodeS3Bucket.Arn
    StellarApiArn:
        Value: !Ref StellarHttpApi.Arn
