AWSTemplateFormatVersion: "2010-09-09"
Parameters:
    EnvType:
        Type: String
        Description: Environment type.
        ConstraintDescription: must specify setup, test, or prod.
    ConfigS3BucketArn:
        Type: String
        Description: ARN of S3 bucket to store config.
    StellarHttpApiArn:
        Type: String
        Description: ARN of API Gateway.
    StellarLambdaApiArn:
        Type: String
        Description: ARN of Lambda.
Resources:
    UpdateStellarStackPolicy:
        Type: "AWS::IAM::Policy"
        Properties:
            PolicyName: "UpdateStellarStack"
            Users:
                - TravisCI
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Sid: StellarLambda
                    Effect: Allow
                    Action:
                        - "lambda:GetFunctionConfiguration"
                        - "lambda:UpdateFunctionConfiguration"
                        - "lambda:UpdateFunctionCode"
                    Resource: !Ref StellarLambdaApiArn
                  - Sid: StellarS3
                    Effect: Allow
                    Action:
                        - "s3:ListBucket"
                        - "s3:ListObjects"
                        - "s3:GetObject"
                    Resource:
                        - !Ref ConfigS3BucketArn
                        - !Sub "${ConfigS3BucketArn}/*"
                  - Sid: StellarCloudFormation
                    Effect: Allow
                    Action:
                        - "cloudformation:CreateChangeSet"
                        - "cloudformation:DescribeChangeSet"
                        - "cloudformation:ValidateTemplate"
                        - "cloudformation:DescribeStacks"
                        - "cloudformation:ExecuteChangeSet"
                    Resource:
                        - !Ref AWS::StackId
                  - Sid: StellarIAM
                    Effect: Allow
                    Action:
                        - "iam:GetRole"
                    Resource: "*"
                  - Sid: StellarApiGateway
                    Effect: Allow
                    Action:
                        - "apigateway:PATCH"
                        - "apigateway:POST"
                        - "apigateway:GET"
                    Resource: !Ref StellarHttpApiArn


