AWSTemplateFormatVersion: "2010-09-09"
Parameters:
    EnvType:
        Type: String
        Description: Environment type.
        ConstraintDescription: must specify setup, test, or prod.
    ConfigS3BucketArn:
        Type: String
        Description: ARN of S3 bucket to store config.
    StellarHttpApiArn:
        Type: String
        Description: ARN of API Gateway.
    StellarLambdaApiArn:
        Type: String
        Description: ARN of Lambda.
Resources:
    UpdateStellarStackPolicy:
        Type: "AWS::IAM::Policy"
        Properties:
            PolicyName: "UpdateStellarStack"
            Users:
                - TravisCI
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Action:
                        - lambda:AddPermission
                        - lambda:RemovePermission
                        - lambda:CreateFunction
                        - lambda:DeleteFunction
                        - lambda:GetFunction
                        - lambda:InvokeFunction
                        - lambda:TagResource
                        - lambda:UntagResource
                        - lambda:GetFunctionConfiguration
                        - lambda:UpdateFunctionConfiguration
                        - lambda:UpdateFunctionCode
                    Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:scd-*"
                  - Effect: Allow
                    Action:
                        - lambda:CreateEventSourceMapping
                        - lambda:DeleteEventSourceMapping
                        - lambda:GetEventSourceMapping
                    Resource:
                        - "*"
                  - Effect: Allow
                    Action:
                        - "s3:ListBucket"
                        - "s3:ListObjects"
                        - "s3:GetObject"
                        - "s3:PutObject"
                    Resource:
                        - !Ref ConfigS3BucketArn
                        - !Sub "${ConfigS3BucketArn}/*"
                        - arn:aws:s3:::travis-build-stage-shared-storage
                        - arn:aws:s3:::travis-build-stage-shared-storage/*
                  - Effect: Allow
                    Action:
                        - "s3:DeleteObject"
                    Resource:
                        - arn:aws:s3:::travis-build-stage-shared-storage/shared/*
                  - Effect: Allow
                    Action:
                        - "cloudformation:CreateChangeSet"
                        - "cloudformation:ExecuteChangeSet"
                    Resource:
                        - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:changeSet/scd*"
                        - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/scd*"
                  - Effect: Allow
                    Action:
                        - "cloudformation:DescribeChangeSet"
                        - "cloudformation:DescribeStacks"
                        - "cloudformation:ValidateTemplate"
                    Resource:
                        - "*"
                  - Effect: Allow
                    Action:
                        - "apigateway:*"
                    Resource: !Sub "arn:aws:apigateway:${AWS::Region}::/*"
                  - Effect: Allow
                    Action:
                        - iam:AttachRolePolicy
                        - iam:DetachRolePolicy
                        - iam:GetRole
                        - iam:PassRole
                    Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/scd-*"


