AWSTemplateFormatVersion: "2010-09-09"
Parameters:
    EnvType:
        Type: String
        Description: Environment type.
        ConstraintDescription: must specify setup, test, or prod.
    ConfigS3BucketArn:
        Type: String
        Description: ARN of S3 bucket to store config.
    StellarHttpApiArn:
        Type: String
        Description: ARN of API Gateway.
    StellarLambdaApiArn:
        Type: String
        Description: ARN of Lambda.
Resources:
    UpdateStellarStackPolicy:
        Type: "AWS::IAM::Policy"
        Properties:
            PolicyName: "UpdateStellarStack"
            Users:
                - TravisCI
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Action:
                        - "lambda:GetFunctionConfiguration"
                        - "lambda:UpdateFunctionConfiguration"
                        - "lambda:UpdateFunctionCode"
                    Resource: !Ref StellarLambdaApiArn
                  - Effect: Allow
                    Action:
                        - "s3:ListBucket"
                        - "s3:ListObjects"
                        - "s3:GetObject"
                        - "s3:PutObject"
                    Resource:
                        - !Ref ConfigS3BucketArn
                        - !Sub "${ConfigS3BucketArn}/*"
                        - arn:aws:s3:::travis-build-stage-shared-storage
                        - arn:aws:s3:::travis-build-stage-shared-storage/*
                  - Effect: Allow
                    Action:
                        - "s3:DeleteObject"
                    Resource:
                        - arn:aws:s3:::travis-build-stage-shared-storage/shared/*
                  - Effect: Allow
                    Action:
                        - "cloudformation:CreateChangeSet"
                        - "cloudformation:DescribeStacks"
                        - "cloudformation:ExecuteChangeSet"
                    Resource:
                        - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*"
                  - Effect: Allow
                    Action:
                        - "cloudformation:DescribeChangeSet"
                        - "cloudformation:ValidateTemplate"
                    Resource:
                        - "*"
                  - Effect: Allow
                    Action:
                        - "iam:GetRole"
                    Resource: "*"
                  - Effect: Allow
                    Action:
                        - "apigateway:PATCH"
                        - "apigateway:POST"
                        - "apigateway:GET"
                    Resource: !Ref StellarHttpApiArn


